using Npgsql;
using Model;
using System.Text.Json;
namespace DataBaseAppBack;

public static class DBTools
{
    private static string connetionString1 = "Host=localhost;Username=postgres;Password=postpast;Database=ForLabs";
    private static string connetionString2 = "Host=localhost;Username=postgres;Password=postpast;Database=ForLabs2";
    private static NpgsqlDataSource dataSource;

    static DBTools()
    {
        ConnectToDB();
    }

    public static async Task<int> CreateTables()
    {
        var sqlstring = "BEGIN; CREATE TABLE IF NOT EXISTS public.\"Customers\" ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), \"firstName\" text COLLATE pg_catalog.\"default\" NOT NULL, \"middleName\" text COLLATE pg_catalog.\"default\" NOT NULL, \"lastName\" text COLLATE pg_catalog.\"default\" NOT NULL, organization text COLLATE pg_catalog.\"default\" NOT NULL, \"phoneNumber\" text COLLATE pg_catalog.\"default\" NOT NULL, accountant text COLLATE pg_catalog.\"default\" NOT NULL, address text COLLATE pg_catalog.\"default\" NOT NULL, CONSTRAINT \"PK_Customers\" PRIMARY KEY (id) ); CREATE TABLE IF NOT EXISTS public.\"Groups\" ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), product_group text COLLATE pg_catalog.\"default\" NOT NULL, CONSTRAINT \"PK_Groups\" PRIMARY KEY (id) ); CREATE TABLE IF NOT EXISTS public.\"Products\" ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), groupid integer NOT NULL, name text COLLATE pg_catalog.\"default\" NOT NULL, ordering text COLLATE pg_catalog.\"default\" NOT NULL, price integer NOT NULL, CONSTRAINT \"PK_Products\" PRIMARY KEY (id) ); CREATE TABLE IF NOT EXISTS public.\"Purchases\" ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), supplierid integer NOT NULL, groupid integer NOT NULL, productid integer NOT NULL, date date NOT NULL, amount integer NOT NULL, sum integer NOT NULL, CONSTRAINT \"PK_Purchases\" PRIMARY KEY (id) ); CREATE TABLE IF NOT EXISTS public.\"Sellings\" ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), customerid integer NOT NULL, groupid integer NOT NULL, productid integer NOT NULL, date date NOT NULL, amount integer NOT NULL, sum integer NOT NULL, CONSTRAINT \"PK_Sellings\" PRIMARY KEY (id) ); CREATE TABLE IF NOT EXISTS public.\"Suppliers\" ( id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ), \"firstName\" text COLLATE pg_catalog.\"default\" NOT NULL, \"middleName\" text COLLATE pg_catalog.\"default\" NOT NULL, \"lastName\" text COLLATE pg_catalog.\"default\" NOT NULL, organization text COLLATE pg_catalog.\"default\" NOT NULL, \"phoneNumber\" text COLLATE pg_catalog.\"default\" NOT NULL, accountant text COLLATE pg_catalog.\"default\" NOT NULL, address text COLLATE pg_catalog.\"default\" NOT NULL, CONSTRAINT \"PK_Suppliers\" PRIMARY KEY (id) ); ALTER TABLE IF EXISTS public.\"Products\" ADD CONSTRAINT \"FK_Products_Groups_groupid\" FOREIGN KEY (groupid) REFERENCES public.\"Groups\" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE; CREATE INDEX IF NOT EXISTS \"IX_Products_groupid\" ON public.\"Products\"(groupid); ALTER TABLE IF EXISTS public.\"Purchases\" ADD CONSTRAINT \"FK_Purchases_Groups_groupid\" FOREIGN KEY (groupid) REFERENCES public.\"Groups\" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE; CREATE INDEX IF NOT EXISTS \"IX_Purchases_groupid\" ON public.\"Purchases\"(groupid); ALTER TABLE IF EXISTS public.\"Purchases\" ADD CONSTRAINT \"FK_Purchases_Products_productid\" FOREIGN KEY (productid) REFERENCES public.\"Products\" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE; CREATE INDEX IF NOT EXISTS \"IX_Purchases_productid\" ON public.\"Purchases\"(productid); ALTER TABLE IF EXISTS public.\"Purchases\" ADD CONSTRAINT \"FK_Purchases_Suppliers_supplierid\" FOREIGN KEY (supplierid) REFERENCES public.\"Suppliers\" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE; CREATE INDEX IF NOT EXISTS \"IX_Purchases_supplierid\" ON public.\"Purchases\"(supplierid); ALTER TABLE IF EXISTS public.\"Sellings\" ADD CONSTRAINT \"FK_Sellings_Customers_customerid\" FOREIGN KEY (customerid) REFERENCES public.\"Customers\" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE; CREATE INDEX IF NOT EXISTS \"IX_Sellings_customerid\" ON public.\"Sellings\"(customerid); ALTER TABLE IF EXISTS public.\"Sellings\" ADD CONSTRAINT \"FK_Sellings_Groups_groupid\" FOREIGN KEY (groupid) REFERENCES public.\"Groups\" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE; CREATE INDEX IF NOT EXISTS \"IX_Sellings_groupid\" ON public.\"Sellings\"(groupid); ALTER TABLE IF EXISTS public.\"Sellings\" ADD CONSTRAINT \"FK_Sellings_Products_productid\" FOREIGN KEY (productid) REFERENCES public.\"Products\" (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE CASCADE; CREATE INDEX IF NOT EXISTS \"IX_Sellings_productid\" ON public.\"Sellings\"(productid); END;";

        using var reader = dataSource.CreateCommand(sqlstring);

        return await reader.ExecuteNonQueryAsync();
    }

    public static int ConnectToDB()
    {
        try
        {
            var dataSourceBuilder = new NpgsqlDataSourceBuilder(connetionString1);
            dataSource = dataSourceBuilder.Build();
        }
        catch
        {
            return 0;
        }
        return 1;
    }

    public static int ConntectToDB2()
    {
        try
        {
            var dataSourceBuilder = new NpgsqlDataSourceBuilder(connetionString2);
            dataSource = dataSourceBuilder.Build();
        }
        catch
        {
            return 0;
        }
        return 1;
    }

    public static async Task<List<UserCredentials>> GetAuthenticate(UserCredentials user)
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM users WHERE username='{user.username}' AND password='{user.password}'").ExecuteReaderAsync();
        var collection = new List<UserCredentials>();

        while (await reader.ReadAsync())
        {
            collection.Add(new UserCredentials(reader.GetInt32(0), reader.GetString(1), reader.GetString(2)));
        }

        return collection; 
    }
    

    public static string TransformWhere(string whereOption)
    {
        return whereOption == "" ? "" : $"WHERE {whereOption}";
    }

    public static async Task<string> GetProductsEnqueued(string whereOption)
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Products\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var collection = new List<Product>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Product(reader.GetInt32(0), reader.GetInt32(1), reader.GetString(2), reader.GetString(3), reader.GetInt32(4)));
        }

        return JsonSerializer.Serialize(collection);
    }

    public static async Task<string> GetGroupsEnqueued(string whereOption)
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Groups\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var collection = new List<Group>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Group(reader.GetInt32(0), reader.GetString(1)));
        }
        
        return JsonSerializer.Serialize(collection);
    }

    public static async Task<string> GetPurchasesEnqueued(string whereOption)
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Purchases\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var collection = new List<Purchase>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Purchase(reader.GetInt32(0), reader.GetInt32(1), reader.GetInt32(2), reader.GetInt32(3), reader.GetDateTime(4), reader.GetInt32(5), reader.GetInt32(6)));
        }

        return JsonSerializer.Serialize(collection);

    }

    public static async Task<List<DbInfo>> GetDbInfo()
    {
        using var reader = await dataSource.CreateCommand(
                $@" 
                    SELECT current_database() AS database_name
                    UNION
                    SELECT setting AS database_location
                    FROM pg_settings
                    WHERE name = 'data_directory'
                    UNION
                    SELECT version() AS database_type;"
                ).ExecuteReaderAsync();

        var students = new List<DbInfo>();

        while (await reader.ReadAsync())
        {
            students.Add(new DbInfo(reader.GetString(0)));
        }

        return students;
    }

    public static async Task<List<TableInfo>> GetTablesInfo()
    {
        using var reader = await dataSource.CreateCommand(
                $@" 

                    SELECT
                        t.relname AS table_name,
                        t.n_live_tup AS row_count,
                        COUNT(c.column_name) AS column_count
                    FROM
                        pg_stat_user_tables t
                    LEFT JOIN
                        information_schema.columns c
                    ON
                        c.table_schema = t.schemaname
                        AND c.table_name = t.relname
                    GROUP BY
                        t.schemaname, t.relname, t.n_live_tup
                    ORDER BY
                        row_count DESC;"
                ).ExecuteReaderAsync();

        var students = new List<TableInfo>();

        while (await reader.ReadAsync())
        {
            students.Add(new TableInfo(reader.GetString(0), reader.GetInt32(1), reader.GetInt32(2)));
        }

        return students;
    }
    

    public static async Task<List<Customer>> GetCustomers(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Customers\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var students = new List<Customer>();

        while (await reader.ReadAsync())
        {
            students.Add(new Customer(reader.GetInt32(0), reader.GetString(1), reader.GetString(2), reader.GetString(3), reader.GetString(4),
reader.GetString(5), reader.GetString(6), reader.GetString(7)
                        ));
        }

        return students;
    }
    
    public static async Task<List<Supplier>> GetSuppliers(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Suppliers\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var students = new List<Supplier>();

        while (await reader.ReadAsync())
        {
            students.Add(new Supplier(reader.GetInt32(0), reader.GetString(1), reader.GetString(2), reader.GetString(3), reader.GetString(4),
reader.GetString(5), reader.GetString(6), reader.GetString(7)
                        ));
        }

        return students;
    }

    public static async Task<List<Group>> GetGroups(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Groups\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var collection = new List<Group>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Group(reader.GetInt32(0), reader.GetString(1)));
        }

        return collection;
    }

    public static async Task<List<Product>> GetProducts(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Products\" {TransformWhere(whereOption)} ORDER BY id;").ExecuteReaderAsync();
        var collection = new List<Product>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Product(reader.GetInt32(0), reader.GetInt32(1), reader.GetString(2), reader.GetString(3), reader.GetInt32(4)));
        }

        return collection;
    }

    public static async Task<List<Task3DTO>> GetProductAmount(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand(
        $@"
            SELECT ""Groups"".id, ""Groups"".product_group, SUM(amount) FROM ""Purchases""
            INNER JOIN ""Groups"" ON ""Purchases"".groupid = ""Groups"".id
            WHERE {whereOption} 
            GROUP BY product_group, ""Groups"".id"

        ).ExecuteReaderAsync();

        var collection = new List<Task3DTO>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Task3DTO(reader.GetInt32(0), reader.GetString(1), reader.GetInt32(2)));
        }

        return collection;
    }

    public static async Task<List<Purchase>> GetPurchases(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Purchases\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var collection = new List<Purchase>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Purchase(reader.GetInt32(0), reader.GetInt32(1), reader.GetInt32(2), reader.GetInt32(3), reader.GetDateTime(4), reader.GetInt32(5), reader.GetInt32(6)));
        }

        return collection;
    }

    public static async Task<List<Task4DTO>> GetPurchasesSumByDate(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand(
        $@"
            SELECT ""Suppliers"".""firstName"", ""Suppliers"".""middleName"", ""Suppliers"".""lastName"",
            ""Purchases"".date, SUM(""Purchases"".sum) FROM ""Purchases""
            INNER JOIN ""Suppliers"" ON ""Suppliers"".id = ""Purchases"".supplierid
            WHERE {whereOption}
            GROUP BY ""firstName"", ""middleName"", ""lastName"", date"

        ).ExecuteReaderAsync();

        var collection = new List<Task4DTO>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Task4DTO(reader.GetString(0), reader.GetString(1), reader.GetString(2),
                        reader.GetDateTime(3), reader.GetInt32(4)
                        ));
        }

        return collection;
    }
    
    public static async Task<List<Selling>> GetSellings(string whereOption = "")
    {
        using var reader = await dataSource.CreateCommand($"SELECT * FROM \"Sellings\" {TransformWhere(whereOption)};").ExecuteReaderAsync();
        var collection = new List<Selling>();

        while (await reader.ReadAsync())
        {
            collection.Add(new Selling(reader.GetInt32(0), reader.GetInt32(1), reader.GetInt32(2), reader.GetInt32(3), reader.GetDateTime(4), reader.GetInt32(5), reader.GetInt32(6)));
        }

        return collection;
    }
    
    public static async Task<int> InsertCustomer(Customer customer)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand("INSERT INTO \"Customers\" (\"firstName\", \"middleName\", \"lastName\", organization, \"phoneNumber\", accountant, address) " + 
        "VALUES ($1, $2, $3, $4, $5, $6, $7);", connection)
        {
            Parameters = 
            {
                new() {Value = customer.firstName},
                new() {Value = customer.middleName},
                new() {Value = customer.lastName},
                new() {Value = customer.organization},
                new() {Value = customer.phoneNumber},
                new() {Value = customer.accountant},
                new() {Value = customer.address}
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }
    
    public static async Task<int> InsertSupplier(Supplier supplier)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand("INSERT INTO \"Suppliers\" (\"firstName\", \"middleName\", \"lastName\", organization, \"phoneNumber\", accountant, address) " + 
        "VALUES ($1, $2, $3, $4, $5, $6, $7);", connection)
        {
            Parameters = 
            {
                new() {Value = supplier.firstName},
                new() {Value = supplier.middleName},
                new() {Value = supplier.lastName},
                new() {Value = supplier.organization},
                new() {Value = supplier.phoneNumber},
                new() {Value = supplier.accountant},
                new() {Value = supplier.address}
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }

    public static async Task<int> InsertProduct(Product product)
    {

        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand("INSERT INTO \"Products\" (name, ordering, price, groupid) " + 
        "VALUES ($1, $2, $3, $4);", connection)
        {
            Parameters = 
            {
                new() {Value = product.name},
                new() {Value = product.ordering},
                new() {Value = product.price},
                new() {Value = product.groupId}
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }
    
    public static async Task<int> InsertGroup(Group group)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand("INSERT INTO \"Groups\" (product_group) " + 
        "VALUES ($1);", connection)
        {
            Parameters = 
            {
                new() {Value = group.product_group},
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }
    
    public static async Task<int> InsertPurchase(Purchase purchase)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand("INSERT INTO \"Purchases\" (supplierid, groupid, productid, date, amount, sum) " + 
        "VALUES ($1, $2, $3, $4, $5, $6);", connection)
        {
            Parameters = 
            {
                new() {Value = purchase.supplierid},
                new() {Value = purchase.groupid},
                new() {Value = purchase.productid},
                new() {Value = purchase.date},
                new() {Value = purchase.amount},
                new() {Value = purchase.sum},
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }
    
    public static async Task<int> InsertSelling(Selling selling)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand("INSERT INTO \"Sellings\" (supplierid, groupid, productid, date, amount, sum) " + 
        "VALUES ($1, $2, $3, $4, $5, $6);", connection)
        {
            Parameters = 
            {
                new() {Value = selling.customerid},
                new() {Value = selling.groupid},
                new() {Value = selling.productid},
                new() {Value = selling.date},
                new() {Value = selling.amount},
                new() {Value = selling.sum},
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }
    
    public static async Task<int> UpdateInTable(string table, int id, List<string> values)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand($"UPDATE \"{table}\" SET {string.Join(',', values.ToArray())} WHERE " + 
        "id = $1;", connection)
        {
            Parameters = 
            {
                new() {Value = id},
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }

    public static async Task<int> UpdateProductsSizeByGroups(int id)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand(
        $@"
            UPDATE ""Products""
            SET price = price - (price / 100)
            WHERE groupid = $1;"
        , connection)
        {
            Parameters =
            {
                new() {Value = id}
            }
        };

        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }

    public static async Task<int> DeleteInTable(string table, int id)
    {
        await using var connection = await dataSource.OpenConnectionAsync();
        await using var cmd = new NpgsqlCommand($"DELETE FROM \"{table}\" WHERE " + 
        "id = $1;", connection)
        {
            Parameters = 
            {
                new() {Value = id},
            }
        };
        var result = await cmd.ExecuteNonQueryAsync();      
        return result;
    }
}
